name: S3 Deploy Stage
on:
  push:
    branches:
      - main
     
jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: "S3 Sync"
        
      env: 
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_DEFAULT_REGION: us-east-1
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      
      uses: ItsKarma/aws-cli@v1.70.0
      with: 
        args: "aws s3 cp  --recursive --region us-east-1 . s3://braveup.co --acl public-read"
